component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/com/.*
- ./bin/com/microstar/.*
- ./bin/com/microstar/xml/.*
- ./bin/de/.*
- ./bin/de/masters_of_disaster/.*
- ./bin/de/masters_of_disaster/ant/.*
- ./bin/de/masters_of_disaster/ant/tasks/.*
- ./bin/de/masters_of_disaster/ant/tasks/ar/.*
- ./bin/de/masters_of_disaster/ant/tasks/calculatesize/.*
- ./bin/de/masters_of_disaster/ant/tasks/deb/.*
- ./bin/doc/.*
- ./bin/doc/FAQ/.*
- ./bin/doc/news43/.*
- ./bin/doc/tips/.*
- ./bin/doc/users-guide/.*
- ./bin/doclet/.*
- ./bin/docs/.*
- ./bin/icons/.*
- ./bin/installer/.*
- ./bin/macosx/.*
- ./bin/macros/.*
- ./bin/macros/C/.*
- ./bin/macros/Clipboard/.*
- ./bin/macros/Editing/.*
- ./bin/macros/Files/.*
- ./bin/macros/Interface/.*
- ./bin/macros/Java/.*
- ./bin/macros/Misc/.*
- ./bin/macros/Properties/.*
- ./bin/macros/Text/.*
- ./bin/modes/.*
- ./bin/net/.*
- ./bin/org/.*
- ./bin/org/gjt/.*
- ./bin/org/gjt/sp/.*
- ./bin/org/gjt/sp/jedit/.*
- ./bin/org/gjt/sp/jedit/browser/.*
- ./bin/org/gjt/sp/jedit/bsh/.*
- ./bin/org/gjt/sp/jedit/bsh/classpath/.*
- ./bin/org/gjt/sp/jedit/bsh/collection/.*
- ./bin/org/gjt/sp/jedit/bsh/commands/.*
- ./bin/org/gjt/sp/jedit/bsh/org/.*
- ./bin/org/gjt/sp/jedit/bsh/org/objectweb/.*
- ./bin/org/gjt/sp/jedit/bsh/org/objectweb/asm/.*
- ./bin/org/gjt/sp/jedit/bsh/reflect/.*
- ./bin/org/gjt/sp/jedit/buffer/.*
- ./bin/org/gjt/sp/jedit/bufferio/.*
- ./bin/org/gjt/sp/jedit/bufferset/.*
- ./bin/org/gjt/sp/jedit/gui/.*
- ./bin/org/gjt/sp/jedit/gui/statusbar/.*
- ./bin/org/gjt/sp/jedit/help/.*
- ./bin/org/gjt/sp/jedit/icons/.*
- ./bin/org/gjt/sp/jedit/icons/themes/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/10x10/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/10x10/actions/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/10x10/emblem/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/10x10/status/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/16x16/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/16x16/actions/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/16x16/devices/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/16x16/mimetypes/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/16x16/places/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/16x16/status/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/22x22/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/22x22/actions/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/22x22/apps/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/22x22/categories/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/22x22/devices/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/22x22/places/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/22x22/status/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/32x32/.*
- ./bin/org/gjt/sp/jedit/icons/themes/classic/32x32/apps/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/10x10/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/10x10/actions/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/10x10/emblem/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/10x10/status/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/16x16/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/16x16/actions/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/16x16/animations/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/16x16/apps/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/16x16/categories/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/16x16/devices/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/16x16/emblem/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/16x16/mimetypes/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/16x16/places/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/16x16/status/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/22x22/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/22x22/actions/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/22x22/animations/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/22x22/apps/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/22x22/categories/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/22x22/devices/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/22x22/emblems/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/22x22/mimetypes/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/22x22/places/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/22x22/status/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/32x32/.*
- ./bin/org/gjt/sp/jedit/icons/themes/tango/32x32/apps/.*
- ./bin/org/gjt/sp/jedit/indent/.*
- ./bin/org/gjt/sp/jedit/input/.*
- ./bin/org/gjt/sp/jedit/io/.*
- ./bin/org/gjt/sp/jedit/menu/.*
- ./bin/org/gjt/sp/jedit/msg/.*
- ./bin/org/gjt/sp/jedit/options/.*
- ./bin/org/gjt/sp/jedit/pluginmgr/.*
- ./bin/org/gjt/sp/jedit/print/.*
- ./bin/org/gjt/sp/jedit/proto/.*
- ./bin/org/gjt/sp/jedit/search/.*
- ./bin/org/gjt/sp/jedit/syntax/.*
- ./bin/org/gjt/sp/jedit/textarea/.*
- ./bin/org/gjt/sp/jedit/visitors/.*
- ./bin/org/gjt/sp/util/.*
- ./bin/package-files/.*
- ./bin/package-files/linux/.*
- ./bin/package-files/linux/deb/.*
- ./bin/package-files/linux/rpm/.*
- ./bin/package-files/linux/slackware/.*
- ./bin/package-files/os2/.*
- ./bin/package-files/windows/.*
- ./bin/properties/.*
- ./bin/startup/.*
- ./build-support/.*
- ./jEdit/.*
- ./jEdit/com/.*
- ./jEdit/com/microstar/.*
- ./jEdit/com/microstar/xml/.*
- ./jEdit/de/.*
- ./jEdit/de/masters_of_disaster/.*
- ./jEdit/de/masters_of_disaster/ant/.*
- ./jEdit/de/masters_of_disaster/ant/tasks/.*
- ./jEdit/de/masters_of_disaster/ant/tasks/ar/.*
- ./jEdit/de/masters_of_disaster/ant/tasks/calculatesize/.*
- ./jEdit/de/masters_of_disaster/ant/tasks/deb/.*
- ./jEdit/doc/.*
- ./jEdit/doc/FAQ/.*
- ./jEdit/doc/news43/.*
- ./jEdit/doc/tips/.*
- ./jEdit/doc/users-guide/.*
- ./jEdit/doclet/.*
- ./jEdit/icons/.*
- ./jEdit/installer/.*
- ./jEdit/jars/.*
- ./jEdit/jars/LatestVersion/.*
- ./jEdit/jars/MacOSX/.*
- ./jEdit/jars/MacOSX/docs/.*
- ./jEdit/jars/MacOSX/macosx/.*
- ./jEdit/jars/QuickNotepad/.*
- ./jEdit/macros/.*
- ./jEdit/macros/C/.*
- ./jEdit/macros/Clipboard/.*
- ./jEdit/macros/Editing/.*
- ./jEdit/macros/Files/.*
- ./jEdit/macros/Interface/.*
- ./jEdit/macros/Java/.*
- ./jEdit/macros/Misc/.*
- ./jEdit/macros/Properties/.*
- ./jEdit/macros/Text/.*
- ./jEdit/modes/.*
- ./jEdit/net/.*
- ./jEdit/org/.*
- ./jEdit/org/gjt/.*
- ./jEdit/org/gjt/sp/.*
- ./jEdit/org/gjt/sp/jedit/.*
- ./jEdit/org/gjt/sp/jedit/browser/.*
- ./jEdit/org/gjt/sp/jedit/bsh/.*
- ./jEdit/org/gjt/sp/jedit/bsh/classpath/.*
- ./jEdit/org/gjt/sp/jedit/bsh/collection/.*
- ./jEdit/org/gjt/sp/jedit/bsh/commands/.*
- ./jEdit/org/gjt/sp/jedit/bsh/org/.*
- ./jEdit/org/gjt/sp/jedit/bsh/org/objectweb/.*
- ./jEdit/org/gjt/sp/jedit/bsh/org/objectweb/asm/.*
- ./jEdit/org/gjt/sp/jedit/bsh/reflect/.*
- ./jEdit/org/gjt/sp/jedit/buffer/.*
- ./jEdit/org/gjt/sp/jedit/bufferio/.*
- ./jEdit/org/gjt/sp/jedit/bufferset/.*
- ./jEdit/org/gjt/sp/jedit/gui/.*
- ./jEdit/org/gjt/sp/jedit/gui/statusbar/.*
- ./jEdit/org/gjt/sp/jedit/help/.*
- ./jEdit/org/gjt/sp/jedit/icons/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/10x10/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/10x10/actions/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/10x10/emblem/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/10x10/status/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/16x16/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/16x16/actions/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/16x16/devices/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/16x16/mimetypes/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/16x16/places/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/16x16/status/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/22x22/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/22x22/actions/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/22x22/apps/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/22x22/categories/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/22x22/devices/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/22x22/places/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/22x22/status/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/32x32/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/classic/32x32/apps/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/10x10/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/10x10/actions/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/10x10/emblem/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/10x10/status/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/16x16/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/16x16/actions/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/16x16/animations/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/16x16/apps/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/16x16/categories/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/16x16/devices/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/16x16/emblem/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/16x16/mimetypes/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/16x16/places/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/16x16/status/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/22x22/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/22x22/actions/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/22x22/animations/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/22x22/apps/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/22x22/categories/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/22x22/devices/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/22x22/emblems/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/22x22/mimetypes/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/22x22/places/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/22x22/status/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/32x32/.*
- ./jEdit/org/gjt/sp/jedit/icons/themes/tango/32x32/apps/.*
- ./jEdit/org/gjt/sp/jedit/indent/.*
- ./jEdit/org/gjt/sp/jedit/input/.*
- ./jEdit/org/gjt/sp/jedit/io/.*
- ./jEdit/org/gjt/sp/jedit/menu/.*
- ./jEdit/org/gjt/sp/jedit/msg/.*
- ./jEdit/org/gjt/sp/jedit/options/.*
- ./jEdit/org/gjt/sp/jedit/pluginmgr/.*
- ./jEdit/org/gjt/sp/jedit/print/.*
- ./jEdit/org/gjt/sp/jedit/proto/.*
- ./jEdit/org/gjt/sp/jedit/search/.*
- ./jEdit/org/gjt/sp/jedit/syntax/.*
- ./jEdit/org/gjt/sp/jedit/textarea/.*
- ./jEdit/org/gjt/sp/jedit/visitors/.*
- ./jEdit/org/gjt/sp/util/.*
- ./jEdit/package-files/.*
- ./jEdit/package-files/linux/.*
- ./jEdit/package-files/linux/deb/.*
- ./jEdit/package-files/linux/rpm/.*
- ./jEdit/package-files/linux/slackware/.*
- ./jEdit/package-files/os2/.*
- ./jEdit/package-files/windows/.*
- ./jEdit/properties/.*
- ./jEdit/startup/.*
- ./lib/.*
